### ISSUE TITLE
DnsCrypt Version?

### ISSUE THREAD

**Issue by hasanalizxc** [Magisk-Modules-Repo/CloudflareDNS4Magisk#1]
Hi there,

It is working good but may i want DnsCrypt version of this?

Thanks.

**Comment by xerta555** [comment]
> It is working good but may i want DnsCrypt version of this?

Hello, sorry for the (very) long reply delay, did i answer you on the XDA thread?

If no, just fork the repo and replace the DNS IP addresses with the other you want.
